### ISSUE TITLE
Can these features be added?

### ISSUE THREAD

**Issue by woducku** [FawazTakahji/Nyaavigator#6]
### Quality of Life Improvements
- **Double-click to Open Details**: Instead of using a drop-down menu, allow users to double-click to open details.
- **Hide Zero Seeds**: Add an option in the settings to hide torrents with zero seeds.

### New Features
- **Submitter Follow System**: Introduce a follow system for submitters with notification support.
- **Sneedex Integration**: Integrate [Sneedex](https://sneedex.moe/) similar to the [NyaaBlue](https://greasyfork.org/en/scripts/441017-nyaablue) script.

<br>

**Current Issue with Opening Details**:
Currently, to view details, I need to use a drop-down menu, which can be cumbersome with repetitive use. Implementing a double-click or single-click option (similar to a browser) would be much more convenient.

![image](https://github.com/FawazTakahji/Nyaavigator/assets/57977673/80c918bb-ee8c-4cec-a96e-304534e5bb65)

**Submitter Notification System**:
Having a notification system for specific submitters would be a valuable addition, potentially attracting more users. Since this feature is not available on the official site, it could be implemented similarly to the qBittorrent RSS feed for notifications (by qBittorent RSS feed i only meant like regex filter. doesn't have to be auto download) or a simple follow tab.

**Comment by FawazTakahji** [comment]
These are great suggestions, I will take a look in my free time, the sneedex thing looks really useful

**Comment by FawazTakahji** [comment]
I've created separate issues for each suggestion to track things easily.
